# Alpine Linux with OpenJDK JRE
FROM openjdk:8-jre-alpine
# copy WAR into image
COPY meribotREST-0.0.1-SNAPSHOT.jar /usr/app/app.jar
WORKDIR /usr/app
# run application with this command line 
CMD ["/usr/bin/java", "-jar", "app.jar"]